---
- hosts: all
  become: yes
  tasks:
  - name: create ansible node
  ec2:
    key_name: Awsfile
    instance_type: t2.micro
    image: ami-02d6f507f59354e5a
    wait: yes
    group: default
    count: 1
    vpc_subnet_id: subnet-03ada1dd3a7b72d7e
    assign_public_ip: yes
    region: ap-south-1
    instance_tags:
      Name: AnsibleNodes