---
- hosts: 172.31.47.149
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: copy file
    copy:
      src: mytest.txt
      dest: /home/ubuntu/my2ndfile

  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: remote file
    get_url:
      url: https://s3demonik.s3.ap-south-1.amazonaws.com/mahalogin/Dockerfile
      dest: /home/ubuntu/Dockerfile
      force_basic_auth: yes

  - name: dyno file
    template:
      src: index.j2
      dest: /var/www/html/index.html