---
- hosts: 172.31.47.149
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: copy file
    copy:
      src: mytest.txt
      dest: /home/ubuntu/my2ndfile

  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: dyno file
    template:
      src: index.j2
      dest: /var/www/html/index.html
    notify: restartwebserver

  handlers:
  - name: restartwebserver
    service:
      name: apache2
      state: restarted
