---
- hosts: server
  become: yes
  tasks:
  - name: install java on ubuntu
    apt:
      name: "{{java}}"
      state: present

  - name: start java  on ubuntu
    service:
      name: "{{java}}"
      state: started

  - name: install webserver on ubuntu
    apt:
      name: "{{webserver}}"
      state: present

  - name: start webserver  on ubuntu
    service:
      name: "{{webserver}}"
      state: started

  - name: install awscli on ubuntu
    apt:
      name: "{{cli}}"
      state: present

  - name: start awscli  on ubuntu
    service:
      name: "{{cli}}"
      state: started      