---
- hosts: 172.31.47.149
  become: yes
  tasks:
  - name: install java on ubuntu
    apt:
      name: "{{java}}"
      state: present
  
  - name: start java on ubuntu
    service:
      name: "{{java}}"
      state: started